instagram/urls.py
from user_profile.views import profile
from django.conf import settings


"""instagram URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.9/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Add an import:  from blog import urls as blog_urls
    2. Import the include() function: from django.conf.urls import url, include
    3. Add a URL to urlpatterns:  url(r'^blog/', include(blog_urls))
"""
from django.conf.urls import url, include
from django.contrib import admin
from .views import home

urlpatterns = [
    url(r'^$', home, name='home-page'),
    url(r'^admin/', admin.site.urls),
    url(r'^profile/', include('user_profile.urls', namespace='profile')),
    url(r'^auth/', include('user_manager.urls', namespace='user_manager')),
    url(r'^api/v1/', include('webservice.urls')),
]


if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

user_manager/urls.py
from django.conf.urls import url
from .views import LoginView, RegisterView, forgot_password

urlpatterns = [
    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^register/$', RegisterView.as_view(), name='register'),
    url(r'^login/forgot$', forgot_password, name='forgot'),
]

user_manager/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from model_utils.models import TimeStampedModel


class Member(AbstractUser):
    phone = models.CharField(max_length=15)  # TODO: add validator
    bio = models.TextField(max_length=500)
    profile_picture = models.ImageField()


class Follow(TimeStampedModel):
    who = models.ForeignKey(Member, null=False, related_name='following')
    whom = models.ForeignKey(Member, null=False, related_name='followers')

    def save(self, *args, **kwargs):
        if self.who != self.whom:
            super(Follow, self).save(*args, **kwargs)
        else:
            raise ValueError('One cannot follow him/her self')

    class Meta:
        unique_together = ('who', 'whom')
        verbose_name = 'دنبال کردن'
        verbose_name_plural = 'دنبال کردن‌ها'


class Comment(TimeStampedModel):
    commenter = models.ForeignKey(Member, null=False, verbose_name=u'کامنت دهنده')
    media = models.ForeignKey('Media', null=False, verbose_name=u'تصویر')
    comment_text = models.TextField(null=False)

    def __str__(self):
        return '{name} commented {text} on {caption}'.format(
            name=self.commenter.get_full_name(),
            text=self.comment_text,
            caption=self.media.caption
        )



class Like(TimeStampedModel):
    liker = models.ForeignKey(Member, null=False)
    media = models.ForeignKey('Media', null=False)

    def __str__(self):
        return '%s likes %s' % (
            self.liker.get_full_name(),
            self.media.caption
        )

    class Meta:
        unique_together = ('liker', 'media')


class HashTag(models.Model):
    caption = models.CharField(max_length=60, verbose_name='عنوان برچسب')

    def __str__(self):
        return self.caption

    class Meta:
        verbose_name = 'برچسب'
        verbose_name_plural = 'برچسب‌ها'


class Media(TimeStampedModel):
    uploader = models.ForeignKey(Member, null=False, related_name='posts')
    file = models.FileField(null=False)
    caption = models.TextField()
    hash_tags = models.ManyToManyField(HashTag)
    comments = models.ManyToManyField(Member, through=Comment, related_name='comments')
    likes = models.ManyToManyField(Member, through=Like, related_name='likes')

    def __str__(self):
        return '{caption} by {name}'.format(
            caption=self.caption,
            name=self.uploader.get_full_name()
        )

user_manager/forms.py
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django import forms
from django.core.exceptions import ValidationError

from user_manager.models import Member


class LoginForm(AuthenticationForm):

    def __init__(self, *args, **kwargs):
        super(LoginForm, self).__init__(*args, **kwargs)
        password_field = self.fields['password']
        username_field = self.fields['username']

        username_field.widget.attrs = {'class': 'inputA'}
        username_field.label = ''

        password_field.widget.attrs = {'class': 'inputA'}
        password_field.label = ''


class RegisterForm(UserCreationForm):

    def clean_phone(self):
        phone_number = self.cleaned_data['phone']
        if len(phone_number) == 0:
            raise ValidationError('Phone number is required')

        if phone_number[0] != '0':
            raise ValidationError('Phone number should begin with a zero')

        return phone_number

    class Meta:
        model = Member
        fields = ['username', 'phone', 'profile_picture', 'email']
        help_texts = {
            'password': 'لطفا گذرواژهٔ امنی انتخاب کنید',
            'bio': 'شرح حال کوتاهی از خود بنویسید',
        }
        labels = {
            'phone': 'شماره همراه',
        }

user_manager/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login as auth_login
from django.views.generic import View
from .forms import LoginForm
from .forms import RegisterForm


class LoginView(View):
    def get(self, request):
        form = LoginForm()
        if request.user.is_authenticated():
            return redirect('profile:profile', username=request.user.username)

        return render(request, 'user_manager/login.html', {
            'form': form
        })

    def post(self, request):
        form = LoginForm(data=request.POST)
        if request.user.is_authenticated():
            return redirect('profile:profile', username=request.user.username)

        if form.is_valid():
            user = form.get_user()
            auth_login(request, user)

            return redirect('profile:profile', username=user.username)

        return render(request, 'user_manager/login.html', {
            'form': form
        })


class RegisterView(View):
    def get(self, request):
        form = RegisterForm()
        return render(request, 'user_manager/register.html', {
            'form': form
        })

    def post(self, request):
        form = RegisterForm(data=request.POST, files=request.FILES)
        if form.is_valid():
            form.save()

            return redirect('user_manager:login')

        return render(request, 'user_manager/register.html', {
            'form': form,
        })


def forgot_password(request):
    pass

user_manager/templates/user_manager/login.html
{% extends 'user_manager/login_register_base.html' %}

{% block page_title %}Log in to instagram{% endblock %}

{% block button_label %}Login{% endblock %}

{% block form_action %}{% url 'user_manager:login' %}{% endblock %}

{% block form_extra %}
<a href="{% url 'user_manager:forgot' %}" class="forget">forget?</a>
{% endblock %}

{% block other_option %}
<p>Don't have an account? <a href="{% url 'user_manager:register' %}">SignUp</a></p>
{% endblock %}

user_manager/templates/user_manager/login_register_base.html
{% extends 'user_profile/user_profile_base.html' %}

{% load static %}


{% block page_title %}Log in to instagram{% endblock %}


{% block css %}
    {{ block.super }}
    <!--<meta http-equiv="refresh" content="2">-->
    <link rel="stylesheet" type="text/css" href="{% static 'user_manager/style/new_style.css' %}"/>
{% endblock %}


{% block page_contents %}
    <!--<div class="absolute">Absolute</div>-->
    <!--<div class="fix">Fixed</div>-->

    <div class="login">
        <div class="form-img"></div>
        <form autocomplete="off" method="post" enctype="multipart/form-data"
              action="{% block form_action %}{% url 'user_manager:login' %}{% endblock %}">
            {% csrf_token %}
            {#        <input class="inputA" placeholder="username" type="text">#}
            {#        <input class="inputA" placeholder="password" type="password">#}
            {#        {{ form.as_p }}#}
            <table>
            {{ form.as_table }}
            </table>
            {% block form_extra %}{% endblock %}
            <input class="inputA" type="submit" value="{% block button_label %}login{% endblock %}">
        </form>
    </div>

    <div class="signup login">
        {% block other_option %}
        {% endblock %}
    </div>
{% endblock %}


{% block js %}{% endblock %}

user_manager/templates/user_manager/register.html
{% extends 'user_manager/login_register_base.html' %}

{% block page_title %}Register in instagram{% endblock %}

{% block button_label %}Register{% endblock %}

{% block form_action %}{% url 'user_manager:register' %}{% endblock %}

{% block form_extra %}
{% endblock %}

{% block other_option %}
<p>Have an account? <a href="{% url 'user_manager:login' %}">Login</a></p>
{% endblock %}